### ISSUE TITLE
Stuck at updating

### ISSUE THREAD

**Issue by TimVanDijk** [arturino009/POEcluster#10]
The tool appears to be stuck while updating.
Probably, poedb.tw has changed and now needs to be parsed differently.

I get the following output:
```
python PoeCluster.py
Didn't find data for current league. Updating...
'option'
```

The code seems to hang on line 54 of updateClusterData.py:
```
for i in allStats['result'][4]['entries'][0]['option']['options']:
```

**Comment by arturino009** [comment]
Fixed in latest update

**Comment by Bonaf1de** [comment]
Alas, I have the same problem in 3.19:

> py poecluster.py
> Didn't find data for current league. Updating...
> 'option'

And then:

> Traceback (most recent call last):
>   File "C:\Downloads\PoeCluster1.1\poecluster.py", line 119, in <module>
>     updateClusterData()
>   File "C:\Downloads\PoeCluster1.1\updateClusterData.py", line 98, in updateClusterData
>     json.dump(get_data_poedb("Small"), outfile)
>   File "C:\Downloads\PoeCluster1.1\updateClusterData.py", line 58, in get_data_poedb
>     for i in allStats['result'][4]['entries'][1]['option']['options']:
> KeyError: 'option'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Downloads\PoeCluster1.1\poecluster.py", line 226, in <module>
>     stop = int(input())
> ValueError: invalid literal for int() with base 10: ''
