### ISSUE TITLE
POE Ninja Requests

### ISSUE THREAD

**Issue by ri-nath** [arturino009/POEcluster#4]
Hey, I noticed that you're getting the rates for each currency individually through scraping. POE Ninja has a hidden api that you can use to request all the currency rates in one request. (Not necessary, but could help in cleaning up the code and improving performance)

With this endpoint, `league_name` would be `'Heist'` and `currency_type` would be `'Currency'`.
```python
f'https://poe.ninja/api/data/currencyoverview?league={league_name}&type={currency_type}'
```

This returns a large JSON object. You can find the chaos equivalent of each currency by doing something like this:
```python
from requests import get
from json import loads as load

response = get('https://poe.ninja/api/data/currencyoverview?league=Heist&type=Currency')
currencies = load(response.text)['lines']

rates = {
     c['currencyTypeName']: c['chaosEquivalent'] for c in currencies
}
```

This would create a dictionary in the format of `{ 'Exalted Orb': 30, 'Orb of Alchemy': 0.2, ...` etc. 
(The reason I didn't implement this myself and make a pull request is because I couldn't get TkinterTreectrl to work... still working on that lol)

**Comment by arturino009** [comment]
Thank you for sharing this! I implemented this now.
